# xxxxxxxxx general vars xxxxxxxxx
export GOPATH=/Users/cvasquez/go
export EDITOR=nvim
export PGPASSWORD=postgres
export PGUSER=postgres
export ANDROID_NDK_HOME="/usr/local/share/android-ndk"
export RAILS_MAX_THREADS=1
export RAILS_MIN_THREADS=1
export ENABLE_RAILS_LOGGER=true
export BROWSER_STACK_USERNAME="xx"
export BROWSER_STACK_ACCESS_KEY="xx"
export SPREEDLY_ENV_3DS=xx
export SPREEDLY_SECRET_3DS=xx
export SPREEDLY_ENV_3DS=xx
export SPREEDLY_SECRET_3DS=xx
export SPREEDLY_SCA_3DS='xx' # Seglan prod with env WfV8miT5c1hA...
export SPREEDLY_SCA_3DS='xx' # Test Prod key
export SPREEDLY_SCA_3DS='xx' # Seglan local key
export SEGLAN_SANDBOX_ROOT_API_KEY='xx'
export CUSTOM_TEST_CARD_NUMBERS='xx'
export FZF_DEFAULT_OPTS='--tmux center'

# xxxxxxxxx $PATH xxxxxxxxx
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/Users/cvazquez/.local/bin
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/usr/local/opt/node@14/bin:$PATH"
export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
FPATH=/usr/local/share/zsh-completions:$FPATH

# xxxxxxxxx alias xxxxxxxxx
alias vim="nvim"
alias cnvim="cd ~/.config/nvim && nvim"
alias cghostty="nvim ~/.config/ghostty/config"
alias czhrc="cd && nvim .zshrc"
alias cat='bat'
alias ls='eza --icons --color=always'
alias ll='eza -lhg --icons --color=always'
alias la='eza -alhg --icons --color=always'
alias ts='task list project:Today'
alias ta='task add project:Today'
alias fv='nvim $(fzf)'
alias dk='docker-compose'
alias fvim='nvim $(fzf --preview "bat --color=always {}")'
alias gco='git branch | grep -v "^\*" | fzf --height=20% --reverse --info=inline | xargs git checkout'
alias gcb='git branch --show-current | pbcopy'
alias gpb='git push origin `gbranch` -f'
alias slides="presenterm --image-protocol kitty-local"
alias rnvim="nvim --clean"
alias brs="bundle exec rails s"
alias yz="yazi"
# alias gcc='gcc-12'

# xxxxxxxxx init programs xxxxxxxxx
eval "$(rbenv init -)"
eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

FPATH=/usr/local/share/zsh/site-functions:$FPATH
. /usr/local/opt/asdf/libexec/asdf.sh

source <(fzf --zsh)

# function to get the current git branch
function gbranch {
  git branch --show-current
}

autoload -Uz compinit
if [ "$(date +'%j')" != "$(stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)" ]; then
    compinit
else
    compinit -C
fi

# accept suggestions with tab
# bindkey '\t' end-of-line

export PATH="/usr/local/opt/llvm@15/bin:$PATH"
export CPPFLAGS="-I/usr/local/opt/llvm@15/include"
export LDFLAGS="-L/usr/local/opt/llvm@15/lib"

eval "$(atuin init zsh --disable-up-arrow)"

# Added by Windsurf
export PATH="/Users/cvazquez/.codeium/windsurf/bin:$PATH"
#zprof

eval "$(starship init zsh)"
