# zmodload zsh/zprof

# xxxxxxxxx general vars xxxxxxxxx
export GOPATH=/Users/cristianvasquez/go
export EDITOR=nvim
export PGPASSWORD=postgres
export PGUSER=postgres
export ANDROID_NDK_HOME="/usr/local/share/android-ndk"
export FZF_DEFAULT_OPTS='--tmux 80%'
export HOMEBREW_NO_AUTO_UPDATE=1
export LANGCHAIN_TRACING_V2=true
#export ASDF_PYTHON_VERSION=3.11.13
#export ASDF_NODEJS_VERSION=24.3.0

# xxxxxxxxx $PATH xxxxxxxxx
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/Users/cristianvasquez/.local/bin
export PATH="/opt/homebrew/opt/node@22/bin:$PATH"

FPATH=/usr/local/share/zsh-completions:$FPATH
FPATH=/usr/local/share/zsh/site-functions:$FPATH

# xxxxxxxxx alias xxxxxxxxx
alias vim="nvim"
alias cnvim="cd ~/.config/nvim && nvim"
alias cghostty="nvim ~/.config/ghostty/config"
alias czhrc="cd && nvim .zshrc"
alias cat='bat'
alias ls='eza --icons --color=always'
alias ll='eza -lhg --icons --color=always'
alias la='eza -alhg --icons --color=always'
alias ts='task list project:Today'
alias ta='task add project:Today'
alias fv='nvim $(fzf)'
alias dk='docker-compose'
alias fvim='nvim $(fzf --preview "bat --color=always {}")'
alias gco='git branch | grep -v "^\*" | fzf --height=20% --reverse --info=inline | xargs git checkout'
alias gcb='git branch --show-current | pbcopy'
alias gpb='git push origin `gbranch` -f'
alias gst='git status'
alias slides="presenterm --image-protocol kitty-local"
alias rnvim="nvim --clean"
alias brs="bundle exec rails s"
alias yz="yazi"

# xxxxxxxxx init programs xxxxxxxxx
eval "$(rbenv init -)"
eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source <(fzf --zsh)
eval "$(atuin init zsh --disable-up-arrow)"
eval "$(starship init zsh)"

# function to get the current git branch
function gbranch {
  git branch --show-current
}

autoload -Uz compinit
if [ "$(date +'%j')" != "$(stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)" ]; then
    compinit
else
    compinit -C
fi

#export PATH="/opt/homebrew/opt/llvm@15/bin:$PATH"
#export LDFLAGS="-L/opt/homebrew/opt/llvm@15/lib"
#export CPPFLAGS="-I/opt/homebrew/opt/llvm@15/include"

#zprof
