require('config.initialize.lualine')
require('config.initialize.trouble')
require('config.initialize.saga')
require('config.initialize.autopairs')
require('config.initialize.kanagawa')
require('config.initialize.nvim_tree')
