require('config.initialize.telescope')
require('config.initialize.treesitter')
require('config.initialize.hop')
require('config.initialize.lualine')
require('config.initialize.trouble')
require('config.initialize.saga')
require('config.initialize.autopairs')
require('config.initialize.kanagawa')
